# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bartvm.github.io/blocks
title: Blocks
email: doesntexist@gmail.com
description: > # "Write an awesome description for your new site here. 
  Blocks is a Theano framework for building and training neural networks.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: docs
    icon: book
    url: https://blocks.readthedocs.org
  - title: github
    icon: github
    url: https://github.com/bartvm/blocks
  - title: download
    icon: download
    url: https://github.com/bartvm/blocks/archive/gh-pages.zip
